### PR TITLE
Upload simple binning suite

### PR DESCRIPTION
**Pull request by sidneymau**
Run farm_simple to produce results, compile results with make_list, and produce plots with render plots. Adjust config as needed

I'll need to update the code that I've written for consistency with the rest of ugali

### CODE REVIEW

**Comment by kadrlica** [comment]
Great, thanks @SidneyMau. @bechtol, you might be interested in this.

**Comment by kadrlica** [comment]
@SidneyMau I think that in your original proposal you were suggesting moving the simple binner code to `ugali/simple` from `ugali/scratch/simple`. (Note, the repository is also named `ugali` so most code is actually located in `ugali/ugali`.) The files that you committed would be located at top-level under `simple`  Was this your intension? Also, to maintain the history of the original simple binner files, it would be better to start with a `git mv` of `ugali/scratch/simple` to `ugali/simple` and then to overwrite the moved files with your new changes. This would serve a few purposes: 1) it would allow git to link the history of the `simple` files with the ones that Keith committed originally, 2) it would remove the vestigial `ugali/scratch/simple` directory. (Be careful to move your new files to a safe place before doing this so you don't delete them by accident.)

**Comment by SidneyMau** [comment]
@kadrlica you're right, that was an oversight on my part. I'll try and redo the changes as suggested.

**Comment by SidneyMau** [comment]
I could try to adapt `compile_results_v3.py` for newer searches, but I think it's fairly list specific, so that might warrant another `.csv` file to load in some known candidates. I never used it for any of the recent searches as it seemed to be redundant with some other parts of the search/association code. I figured we could leave it in the `extra` (or some other name) folder for now, and if we feel we need to for BLISS/MagLiteS/etc..., then I could adapt it for those purposes.

**Comment by kadrlica** [comment]
Sounds good to me.

**Pull request merged**
