### PR TITLE
Compute extension_radial posterior directly and use this for parameter estimates, as opposed to using extension+ellipticity summary statistics 

### PR DESCRIPTION
**Pull request by willcerny**
Compute extension_radial posterior directly and use this for parameter estimates, as opposed to using extension+ellipticity summary statistics.

Two part solution - first, add storage of extension_radial samples to ugali.utils.stats's Samples class, and then add handling of results in ugali.analysis.results

### CODE REVIEW

**Comment by kadrlica** [comment]
@chinyitan heads up on these (we'd like to make calculations consistent in future analyses). Happy to add you as a collaborator if you would be willing to review this PR.

**Comment by willcerny** [comment]
It'd be good to address PR #97 as well, although from extensive testing it doesn't seem like it matters too much in the end.

**Comment by kadrlica** [comment]
Let's talk about PR #97 on that issue.

**Comment by kadrlica** [comment]
I'm going to close and reopen this to see if I can trigger the test workflow to run.

**Pull request merged**
